/**
 * Typed Host API surface for Shell ↔ Host (architecture §6–§7).
 * Renderer must only invoke these methods via IPC — never spawn grok.
 */

export const HOST_IPC_CHANNEL = "grok-desktop-host" as const;

export type HostIpcMethod =
  // system
  | "system.grokInfo"
  | "system.auth.status"
  | "system.auth.login"
  | "system.auth.logout"
  | "providers.list"
  | "providers.upsert"
  | "providers.remove"
  | "providers.setDefault"
  | "providers.listRemoteModels"
  | "system.openInEditor"
  | "system.openPath"
  | "system.listEditors"
  | "system.openExternal"
  | "system.pickDirectory"
  | "system.pickFiles"
  | "files.read"
  | "files.write"
  | "files.writePasteImage"
  | "files.readDataUrl"
  | "files.list"
  | "files.search"
  | "files.watchStart"
  | "files.watchStop"
  | "singleInstance.status"
  | "config.get"
  | "config.patch"
  // projects
  | "projects.list"
  | "projects.add"
  | "projects.update"
  | "projects.remove"
  // threads / turns
  | "threads.create"
  | "threads.attach"
  | "threads.continueRecent"
  | "threads.detach"
  | "threads.list"
  | "threads.rename"
  | "threads.export"
  | "threads.pin"
  | "threads.archive"
  | "threads.delete"
  | "threads.stop"
  | "threads.setMode"
  | "threads.setModel"
  | "threads.rewindPoints"
  | "threads.rewindPreview"
  | "threads.rewind"
  | "session.context"
  | "turns.prompt"
  | "turns.cancel"
  | "permissions.respond"
  | "history.load"
  // roster / inbox
  | "roster.list"
  | "inbox.list"
  | "inbox.markRead"
  | "inbox.markAllRead"
  | "inbox.dismiss"
  // worktrees / changes
  | "worktrees.list"
  | "worktrees.create"
  | "worktrees.cleanup"
  | "changes.summary"
  | "changes.diff"
  | "changes.timeline"
  // goals / plans / subagents
  | "goals.get"
  | "goals.set"
  | "goals.setStatus"
  | "goals.sync"
  | "goals.clear"
  | "plans.get"
  | "plans.write"
  | "plans.approve"
  | "plans.reject"
  | "plans.respond"
  | "subagents.tree"
  // automations
  | "automations.list"
  | "automations.create"
  | "automations.update"
  | "automations.delete"
  | "automations.pause"
  | "automations.runNow"
  | "automations.listRuns"
  // extensibility（CLI 同源 plugin / skill / mcp / marketplace）
  | "skills.list"
  | "plugins.list"
  | "plugins.install"
  | "plugins.uninstall"
  | "plugins.enable"
  | "plugins.disable"
  | "plugins.update"
  | "plugins.details"
  | "plugins.marketplace.list"
  | "plugins.marketplace.add"
  | "plugins.marketplace.remove"
  | "plugins.marketplace.update"
  | "mcp.list"
  | "mcp.add"
  | "mcp.remove"
  | "mcp.doctor"
  | "models.list"
  // S5 graph / memory
  | "graph.status"
  | "graph.search"
  | "graph.neighborhood"
  | "memory.status"
  | "memory.list"
  | "memory.search"
  | "memory.add"
  | "memory.delete"
  | "memory.setEnabled"
  // S6 shell
  | "shell.trayBadge"
  | "shell.parseDeepLink"
  | "shell.versionMatrix"
  | "shell.readHandoff"
  // S7 PR / remote
  | "pr.list"
  | "pr.diff"
  | "remote.list"
  | "remote.add"
  | "remote.remove";

export const HOST_EVENT_CHANNEL = "grok-desktop-host-event" as const;
